# Configuration for development tooling
[tool.black]
line-length = 100
target-version = ["py310"]

# MyPy parses TOML badly.
# You must use underscores!
[tool.mypy]
python_version = "3.10"
ignore_missing_imports = true
exclude = []

[tool.ruff]
line-length = 100
target-version = "py310"
extend-exclude = []
